FROM python:3.10-slim

WORKDIR /app

COPY req_app_env1.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .
COPY model.h5 .
RUN mkdir temp

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
